Quiz Table refactor
Brightspace/insights-assessment-quality-dashboard pull request #26
Opened 2021-06-14 13:09 UTC by JikaiLong

Refactored the table component to its own component. 

The table component takes 3 input parameters:
1. `tableData`: raw data that the table uses to display 
2. `tableConfig`:
  -`heading`: string or html template
  -`columnHeaders`: list of strings or templates
  -`displayData`: an string entry to the given data set, set it to null when directly passing array of data
  -`detaildataAttr`: list of objects - {`element`: attribute string or list of templates, `option`: 'template or null}
3. `skeleton` : boolean for skeleton template

Sample usage: 

```

const serverData = new QuizData({ metronEndpoint: undefined });
serverData.loadData([6606, 6608], 1386);
const myTableConfig= {
		heading: 'quiz',
		columnHeaders: [
			'first column', 'second column'
		],
		displayData: 'quizzes',
		detaildataAttr: [
			{ element: 'averageScore', option: null },
			{ element: 'reliabilityCoefficient', option: null },
		]
	};

<assessment-quiz-table .tableData = ${serverData} .tableConfig = ${myTableConfig} ?skeleton = false ></assessment-quiz-table>

```
Functional Testing
All component: heading, column headers and table cells are unit tested. You can find the Unit test cases in test/components/assessment-quiz-table.

Performance
No difference, all visual diff tests passed.

Security
No change

Dev-Ops
NA

Cost
NA

UX
NA

2021-06-14 14:15 UTC, NicholasHallman commented
It's not immediately obviouse to me what the detailDataAttr is doing. Also does this PR add the styling configurations we need for rows and columns? I'm curiouse how we can dynamically color a data entry in a column using the API provided.

2021-06-14 14:25 UTC, JikaiLong commented
> It's not immediately obviouse to me what the detailDataAttr is doing. Also does this PR add the styling configurations we need for rows and columns? I'm curiouse how we can dynamically color a data entry in a column using the API provided.

The detailDataAttr is the data attribute that the table will be used to display. Say you want to display `serverData.quizzes ` then the detailDataAttr will be `'quizzes'`, it is an optional thing, if set to null, then `serverData.quizzes ` can passed directly into the table. 

data entry color is done in the parent class. 
For example, you could pass the follow template to the table using the tableConfig.heading
```
	const customHeader = html`
	<style>
	.custom-column-header {font-size: 50px; color: red }
	</style>
	<div class = 'custom-column-header' @click=${openclick} @keypress=${openclick}> custom column header</div>` ;
```

2021-06-14 14:31 UTC, NicholasHallman commented
> The detailDataAttr is the data attribute that the table will be used to display. Say you want to display serverData.quizzes then the detailDataAttr will be 'quizzes', it is an optional thing, if set to null, then serverData.quizzes can passed directly into the table. It could have a better name I suppose.

2021-06-14 14:35 UTC, NicholasHallman commented
> The detailDataAttr is the data attribute that the table will be used to display. Say you want to display serverData.quizzes then the detailDataAttr will be 'quizzes', it is an optional thing, if set to null, then serverData.quizzes can passed directly into the table. It could have a better name I suppose.

Personally, I think this is a little over complicated. Instead of telling the element how to pick data out of a large object we should be taking the required pieces out of the serverData and passing those into the table instead. I see that you did it this way so that the table isn't dependent on any specific object structure (which is great because it helps keep the component pure) but I think this is a round about way of acheiving that

> data entry color is done in the parent class.
For example, you could pass the follow template to the table using the tableConfig.heading

Your example for coloring the header works great because the header would get passed in as a tempalte. But how would we color the data elements? If the table only gets serverData and therefore raw values how do we tell it when we want those values to be styled or not?

2021-06-14 14:52 UTC, JikaiLong commented
> Personally, I think this is a little over complicated. Instead of telling the element how to pick data out of a large object we should be taking the required pieces out of the serverData and passing those into the table instead. I see that you did it this way so that the table isn't dependent on any specific object structure (which is great because it helps keep the component pure) but I think this is a round about way of acheiving that
>

Sorry, I miss read and thought you mean the displayData which is responsible for the the `serverData.quizzes` selection. The `detailDataAttr` is for template and data-entry passing. 

> Your example for coloring the header works great because the header would get passed in as a tempalte. But how would we color the data elements? If the table only gets serverData and therefore raw values how do we tell it when we want those values to be styled or not?
>

The template is actually a bit complicated. I was worrying about things like Quiz headers where they will take parameters like `id` and `name` and lots of local components to construct a single table cell. So instead, a list of component templates is created outside of the table, where they are passed in and the table is only responsible for rendering them. 
For example: we have this function `RenderComplexTemplate(inputdata)` which returns a very complex component for a single cell that has multiple functionalities like redirect to other pages.
then the parent should created a list like `[RenderComplexTemplate(data[0]), RenderComplexTemplate(data[1]), ....]` and passed to `detailDataAttr[0]` if this template is used for the first column.

2021-06-14 15:00 UTC, NicholasHallman commented
> Sorry, I miss read and thought you mean the displayData which is responsible for the the serverData.quizzes selection. The detailDataAttr is for template and data-entry passing.

In that case I think we should get rid of displayData

>  RenderComplexTemplate(inputdata) which returns a very complex component for a single cell that has multiple functionalities like redirect to other pages.

So in this case, we would pre-process serverData, iterating through the data and converting it into tempaltes for the table to use. In that case how do we style the td element that the table wraps? When we highlight a data point blue or red the whole table square is colored is that possible here?

2021-06-14 15:05 UTC, NicholasHallman commented on components/table/assessment-quiz-table.js
> +			return dataAttr.element[index];
I see in this case we expect the parent templating function's to return a TD Element

2021-06-14 15:08 UTC, NicholasHallman commented on components/table/assessment-quiz-table.js
> +			${this.tableConfig.detaildataAttr.map(dataAttr => this._renderTableCell(item, dataAttr, index))}
Maybe a better name for detailedDataAttr would be rowOptions? Makes it a little easier to understand what it is working on

2021-06-14 15:08 UTC, JikaiLong commented
> In that case I think we should get rid of displayData
Yes, that makes sense. Will remove it. 

> So in this case, we would pre-process serverData, iterating through the data and converting it into tempaltes for the table to use. In that case how do we style the td element that the table wraps? When we highlight a data point blue or red the whole table square is colored is that possible here?
The parent actually creates and passes the `<td></td>` element into the table where they can style the element outside of the table. 
So you mean the `<td></td> `element shouldn't get passed from the parent? I could make a separated CSS config attribute to the cell but that means config structure will be more complex.

2021-06-14 15:09 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +			return dataAttr.element[index];
Yes.

2021-06-14 15:09 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +			${this.tableConfig.detaildataAttr.map(dataAttr => this._renderTableCell(item, dataAttr, index))}
Sounds good, I was trying to figure out a better name but had nothing in mind.

2021-06-14 15:18 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +			${this.tableConfig.detaildataAttr.map(dataAttr => this._renderTableCell(item, dataAttr, index))}
Actually it is not ROW options, it is used to target columns, so columnOptions seems better

2021-06-14 15:19 UTC, NicholasHallman commented
> So you mean the `<td></td>` element shouldn't get passed from the parent? I could make a separated CSS config attribute to the cell but that means config structure will be more complex.

Yeah I don't think we should rely on the developer who is using the table to pass td elements in if they want to change the styling. I'm under the impression that the table should supply the structure and default styles and passing in your own structrue could ruin the accessbility of the table.

2021-06-14 15:22 UTC, JikaiLong commented
> Yeah I don't think we should rely on the developer who is using the table to pass td elements in if they want to change the styling. I'm under the impression that the table should supply the structure and default styles and passing in your own structrue could ruin the accessbility of the table.
>
I could add a new config to add style to td but it should specifically tells which cell needs to be styled.

2021-06-14 15:27 UTC, NicholasHallman commented
I think we should supply functions that can run over the data in a row or column and spit out a styleMap and the formatted data given some set of options.

i.e

```javascript
render() {
  // run by the table to dynamically determine the styling of a piece of data
  const formatColumn1 = (data) => {
    const formtedValue = data + '%'; // format value as a percent
    const style = styleMap({
      'background-color': data > 10 ? 'blue' : 'red'
    });
    return { value: formatedValue, style }
  }
  const column1Template = this.tableHeaderWithTooltip('column 1'); // format the header into a template with tooltips
  const options = {
    headers: [column1Template, column2Template],
    columnFormat: [ formatColumn1, formatColumn2 ],
  }

  return html`<assessment-quiz-table data=${data} options=${options}></assessment-quiz-table>`
}
```

2021-06-14 15:38 UTC, JikaiLong commented
> I think we should supply functions that can run over the data in a row or column and spit out a styleMap and the formatted data given some set of options.
> 
Sounds good to me. In the mapping function, the data will be a data entry for the entire row since one custom cell may take multiple attributes from that row.

2021-06-14 15:49 UTC, NicholasHallman commented
>  the data will be a data entry for the entire row since one custom cell may take multiple attributes from that row.

I'm not sure I understand what you mean. I was thinking that as the table rendered each cell it would take the formatting function for that column and run it over the data to go into that cell. i.e

``` javascript
// inside assessment-quality-table
function _renderCell(data, formatFunction) {
  let { value, style } = formatFunction(data);
  return html`<td style=${style}> ${value} </td>`;
}

function _renderRow(rowNum) {
  let cells = []; 
  let lengthOfRow = this.options.headers.length;
  for (let i = 0; i < lengthOfRow; i++){
    cells.push(this._renderCell( this.data[rowNum][i], this.options.columnFormat[i] ));
  }
  return html`<tr>${cells}</tr>`
}
```

If we want multiple kinds of attributes we can encode that into the data. For example an element that includes a link could look like

```javascript
// data is the text, and the href in an array
// example: [ 'home', '/' ]
const formatFunction(data) {
  return { value: html`<a href=${data[1]}>${data[0]</a>}`
}
```

2021-06-14 15:58 UTC, JikaiLong commented
> I'm not sure I understand what you mean. I was thinking that as the table rendered each cell it would take the formatting function for that column and run it over the data to go into that cell. i.e
> 
Yes. I basically meant that.

> If we want multiple kinds of attributes we can encode that into the data. For example an element that includes a link could look like
> 
Right, I am going to do something similar to the quizHeaders.

2021-06-14 16:15 UTC, Vitalii-Misechko commented
Just a reminder that it's important to add all team members into FYI for each PR review

> FYI @anhill-D2L @hyehayes @johngwilkinson @NicholasHallman @bemailloux @JikaiLong @SEsseltine

2021-06-14 16:23 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +			isDemo: { type: Boolean, attribute: 'demo' },
I believe we can get rid of `isDemo` inside the table component.

2021-06-14 16:26 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +		${this._renderQuizDetailsTable()}
`minor`:  we can inline all the code right here. There are no benefits of the existence of `_renderQuizDetailsTable`

2021-06-14 16:33 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +		return this.tableData;
Looks a bit complicated. I believe we can make a more simple code design. It's up to a developer to provide and format the necessary data for the component. Therefore, a single property for data should be enough.

2021-06-14 16:35 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +	</thead>
Using magic numbers is [a code smell.](https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad) Try to avoid them

2021-06-14 16:35 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +	</thead>
`nit`: could you also fix formatting

2021-06-14 16:36 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +		return this.tableData;
Yes. Nick pointed it out as well. I already removed it.

2021-06-14 16:39 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +	</thead>
The problem is that if I do not use `<th>${this._columnHeaders[0]}</th>` to initialize the first cell, the header structure is not displayed for some reason.

2021-06-14 16:42 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +			]
I see two types of elements in `detaildataAttr`:
1. `{ element: string: option: null }`
2. `{ element: string: opton: 'template' }` - special case type

I would suggest splitting these types. The special case type can be a separate property/array

2021-06-14 16:50 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +		this.tableConfig.detaildataAttr[0].element = template;
`minor` 
1. AFAIK, we don't use snake_case. 
2. `template` is not reused. no need to declare this const
3. magic numbers is a code smell

2021-06-14 16:53 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +	_renderHeaderWithToolTip(uniqueId, headerLangTerm, tooltipTextLangTerm) {
this code should be moved into table componenent. `tooltipId` can be generated as `d2l-table-tooltip-${columnNumber}-${rowId}`

2021-06-14 17:03 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +	_d2l_table_quiz_name_header(data) {
I assume the code inside of this method will be repeated as many times as the number of rows. If so we need to reconsider this solution. You might be interested in how this was solved in [d2l-insights-table](https://github.com/Brightspace/insights-engagement-dashboard/blob/06ad425e7ca502c89e59cff85427e9b61a86aaf5/components/table.js)

2021-06-14 17:13 UTC, JikaiLong commented on pages/assessment-quality-dashboard-view.js
> +	_d2l_table_quiz_name_header(data) {
I just checked the rendercell function:
https://github.com/Brightspace/insights-engagement-dashboard/blob/06ad425e7ca502c89e59cff85427e9b61a86aaf5/components/table.js#L216 
and the code is also getting called multiple times from this call `${this.columnInfo.map(this._renderHeaderCell, this)}`, so I wonder what would be a better fix for this?

2021-06-14 17:21 UTC, JikaiLong commented on pages/assessment-quality-dashboard-view.js
> +	_renderHeaderWithToolTip(uniqueId, headerLangTerm, tooltipTextLangTerm) {
But then the parent is required to pass `uniqueId, headerLangTerm, tooltipTextLangTerm` into the table component for it to render. And the header component also takes templates as input, so passing these parameters into the table component seems a bit duplicate I think.

2021-06-15 12:26 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +	_renderHeaderWithToolTip(uniqueId, headerLangTerm, tooltipTextLangTerm) {
> But then the parent is required to pass uniqueId, headerLangTerm, tooltipTextLangTerm into the table component for it to render. 

* Component design. Essentially it's natural/idiomatic to me that the code provides columns' descriptions for the table component. A column description can contain (but not limited to) column name, type, column header/value formatter, tooltip text etc. 
* Regarding `uniqueId`. It rather unique **column** id. In this case, column index or column name is totally fine.

> And the header component also takes templates as input, so passing these parameters into the table component seems a bit duplicate I think.

* Component design. IMHO, the code should not provide a header tooltip template as a parameter of the table component because there is a simpler implementation when `_renderHeaderWithToolTip` is a part of the table component.  

```JS
// alternative implementation of
_renderallColumnHeaders()
	return html`			
		<thead>
			${this.columnHeaders.map(
			(header, idx) =>  header.tooltipTextLangTerm
			  ? this._renderHeaderWithToolTip(idx, header.headerLangTerm, header.tooltipTextLangTerm) 
			  : html`<th>${this.localize(header.headerLangTerm)}</th>`)
		</thead>`
```

2021-06-15 12:41 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +	_d2l_table_quiz_name_header(data) {
Sorry, I didn't bring enough context. I meant to say that I suspect that this code includes `<script>` HTML many times in the component output which is not good. We could introduce rendering similar to `d2l-insights-table` [implementation](https://github.com/Brightspace/insights-engagement-dashboard/blob/06ad425e7ca502c89e59cff85427e9b61a86aaf5/components/table.js#L317) and move this code inside the table component avoiding excessive code generation

```JS
if (columnType === COLUMN_TYPES.ROW_SELECTOR) {
/// One type of rendering
} else if (columnType === COLUMN_TYPES.TEXT_SUB_TEXT) {
...
} else {
// general type of cell rendering
}
```

2021-06-15 14:08 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +	</thead>
I am still stuck on fixing this one. Apparently using a loop(map) to create component is not going to generate the entry point tag for the first row `d2l-table-cell-first` and first cell `d2-table-cell-first`, therefore the table format will not applied to any of those headers.  However, the first cell must be defined manually not in a loop to have a tag on its creation.

2021-06-15 14:33 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +	</thead>
update: fix them by auto assign class tags similar to engagement dashboard

2021-06-15 14:54 UTC, JikaiLong commented
Update:
The new config file now looks like  this:
```
this.tableConfig = {
	heading: '',
	columnHeaders: [
		{ headerLangTerm: 'dashboard:quizDetailsQuiz', tooltipTextLangTerm: null },
		{ headerLangTerm: 'dashboard:quizDetailsAverageScore', tooltipTextLangTerm: null },
		{ headerLangTerm:  'dashboard:quizDetailsReliabilityCoefficient', tooltipTextLangTerm: 'dashboard:quizDetailsReliabilityCoefficientTooltip' },
	],
	columnCellValues:[
		null,
		'averageScore',
		'reliabilityCoefficient',
	],
	columnCellFormat: [
		format_d2l_table_quiz_name_header,
		null,
		null,
	],
};
```
where `format_d2l_table_quiz_name_header` is a function that takes data of a row and render a cell component, it returns a html template for content render and a `styleMap ` which is used to customize the cell itself: such as background color of the cell.

2021-06-15 15:19 UTC, NicholasHallman commented
What does `columnCellValues` do ?

2021-06-15 15:29 UTC, JikaiLong commented
> What does `columnCellValues` do ?

They are attributes of the data to be displayed. like quizzes.averageScore.

2021-06-15 16:26 UTC, Vitalii-Misechko commented
This is unfortunate, but it seems my merge to master created merge conflict here

2021-06-15 16:29 UTC, JikaiLong commented
> This is unfortunate, but it seems my merge to master created merge conflict here

Yea. I think I could either move the pagination part into the table or keep it outside in the dashboard view page. What do you think?

2021-06-15 16:55 UTC, Vitalii-Misechko commented
> > This is unfortunate, but it seems my merge to master created merge conflict here
> 
> Yea. I think I could either move the pagination part into the table or keep it outside in the dashboard view page. What do you think?

Let's keep it outside for simplicity. We can make another refactoring later if we change our mind

2021-06-15 17:16 UTC, JikaiLong commented
Conflict resolved. Now table should work with pagination.

2021-06-15 17:35 UTC, Vitalii-Misechko requested changes

2021-06-15 17:35 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
The main question is what kind of component we are trying to build here? If this is some kind of general table component and it is going to be used D2L -wide then this approach with external value formatter looks good, but the component design should be discussed with Dave Lockhard. If this is an application-wide component that is used only in AQ Dashboard then this is a bit overkill.

I assume we're building an application-wide component. Therefore, this code should be a part of the table component.

```JS
	_renderTableCell(row_item, attr, column_index) {
	        const columnType = this.tableConfig.columnType[column_index]

		if (columnType === ColumnTypes.CLICKABLE_QUIZ_NAME) {
			return this.format_d2l_table_quiz_name_header(row_item)`;
		}

		return html`<td>${row_item[attr]}</td>`;
	}
```

2021-06-15 17:35 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
`nit` Could you go over your PR and 

1. replace `snake_case `with `camelCase`? `SCREAMING_SNAKE_CASE` is used for constants.
2. remove space in attribute assignments for html code. For instantce, rplace this `<tr class = 'd2l-class-name'>` with this `<tr class='d2l-class-name'>`

2021-06-15 17:35 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +			columnCellValues:[
`nit` can we rename `columnCellValues` to `columnValuePropertyNames` or `columnValueGetters`

2021-06-15 17:42 UTC, NicholasHallman commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
The reason I suggested the formatters was because this table has a bunch of different ways of displaying data and we this PR doesn't pre-process the data. Theres two ways to do this

1. We iterate through the data, and turn it into the format we want pre-emptively (like we do for highcharts and in engagement)
2. We give lambdas that format to a specification.

The ways we format data in the table are
- Cells can be colored red
- That little red posfix dot
- Links, tooltips, etc

So we either do it before, of during render. TBH Before is probably better. Since we can use mobx to compute it and pass in a processed data array for the table to draw and not the serverdata object

2021-06-15 17:42 UTC, JikaiLong commented on pages/assessment-quality-dashboard-view.js
> +			columnCellValues:[
columnValuePropertyNames sounds good.

2021-06-15 17:42 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +			: html`<th class = ${ idx === 0 ? 'd2l-table-cell-first' : null }>${this.localize(header.headerLangTerm)}</th>`))}
`nit` Have you considered using `classMap`? Here is an [example](https://github.com/Brightspace/insights-engagement-dashboard/blob/06ad425e7ca502c89e59cff85427e9b61a86aaf5/components/table.js#L296)

2021-06-15 17:47 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +			: html`<th class = ${ idx === 0 ? 'd2l-table-cell-first' : null }>${this.localize(header.headerLangTerm)}</th>`))}
I see. classMap is definitely better. Thanks for letting me know.

2021-06-15 17:51 UTC, JikaiLong commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
Just a bit curious: the column type in the engagement dashboard has the following properties:

<!--StartFragment-->export const COLUMN_TYPES = {	ROW_SELECTOR: -1,	NORMAL_TEXT: 0,	TEXT_SUB_TEXT: 1,	SUB_COLUMNS: 2};<br class="Apple-interchange-newline"><!--EndFragment-->

Should I create my own property or use one of these?

2021-06-15 18:00 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
> The reason I suggested the formatters was because this table has a bunch of different ways of displaying data and we this PR doesn't pre-process the data. Theres two ways to do this

I see. Lambdas are great and powerful and can reduce the complexity of the component. If you guys feel that this is the right design for this component I don't have strong objections against it. If you hesitate I would suggest 'selling' this design idea to John or Bryan. If you succeed you will be sure that it's optimal in our team.

2021-06-15 18:01 UTC, NicholasHallman commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
Hmm it's a little more complicated then I had thought since the api has changed a lot between these two projects...

2021-06-15 18:14 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
> Just a bit curious: the column type in the engagement dashboard has the following properties:
> `ROW_SELECTOR: -1, NORMAL_TEXT: 0, TEXT_SUB_TEXT: 1, SUB_COLUMNS: 2`
> Should I create my own property or use one of these?

These are good examples but I believe we will end up with a bit different types.

2021-06-15 18:39 UTC, JikaiLong commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
So here are two options:

1. Create a list of html cell templates using our current data, and pass them into the table then let the table iterate through each of them to display
2. Create a lambda function and pass it into the table, the table takes the function and input data, then use this function to render html cell templates and display

I asked @bemailloux  about two different ways of design and here is his response:

"There's a more rigid approach you could consider (which is basically (1) but possibly a bit more organized / less flexible). For every table cell type you want to consider, create a LitElement component for it. Then have the table component decide which table cell component to use for each column.

So I'd consider (1) or my alternative. I'm not a fan of (2) because it just doesn't really fit the "components" paradigm. If you're going to pass in a rendering lambda for each column type, you may as well just turn it into a component."

What do you guys think? @Vitalii-Misechko  @NicholasHallman

2021-06-16 08:43 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +		const format_d2l_table_quiz_name_header = (data) => {
I would love to see implemented option (1). But, I'm fine with any of your choice.

2021-06-16 14:15 UTC, JikaiLong commented
Update:
All template are passed in as lambdas.
New config file looks like this:

```
const noStyle = styleMap();
const averageScoreTemplate = (data) => { return { value: html`<div>${data.averageScore}</div>`, noStyle };};
const tableConfig= {
		heading: 'quiz',
		columnHeaders: [
			{ headerLangTerm: 'dashboard:quizDetailsQuiz', tooltipTextLangTerm: null }
		],
		columnCellFormat: [averageScoreTemplate]
};
```
Test Cases Updated. 
Code styles and minor things are fixed.

2021-06-16 15:43 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +			: html`<th class=${ idx === 0 ? classMap(styleFirstCell) : '' }>${this.localize(header.headerLangTerm)}</th>`))}
Let me suggest one minor improvement 
```JS
                const styleFirstCell = (idx) => ({ 'd2l-table-cell-first': idx === 0 });
                ....
				: html`<th class=${classMap(styleFirstCell(idx))}>${this.localize(header.headerLangTerm)}</th>`))}


```

2021-06-16 15:44 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +			: html`<th class=${ idx === 0 ? classMap(styleFirstCell) : '' }>${this.localize(header.headerLangTerm)}</th>`))}
I didn't check the code so it might not work ;)

2021-06-16 15:46 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +			<tr class=${classMap(styleFirstRow)}>
`minor` this line `<tr class=${classMap(styleFirstRow)}>` does not have any benefits over simpler version `<tr class='d2l-table-cell-first'>`. So I'd suggest using simple version

2021-06-16 15:49 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +	)}
`nit` inconsistent indentation

2021-06-16 15:55 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +			const formatedValue =  html`
`Suggestion`. What if we add `tableConfig.sharedStyles` and pass all styles below only once in order to avoid multiple inclusions of this code (code between script tags) into the component output. We could render these styles like the following code.
```JS
 	render() {
		return html`
		${this.tableConfig.sharedStyles}
		<h2 class="d2l-heading-3">${this.tableConfig.heading}</h2>
```

2021-06-16 15:59 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +			></d2l-labs-pagination>
`nit` inconsistent formatting:
* extra spaces for attribute assignemts for `assessment-quiz-table`
* it seems inconsisten indentation for `d2l-labs-pagination`

```JS
// proper indentation
<d2l-labs-pagination
  show-item-count-select
  item-count-options="[10,20,50,100]"
```

2021-06-16 16:02 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +serverData.loadData([6606, 6608], 1386);
`nit` you basically can write `serverData.loadData({})` now. These test parameters `[6606, 6608], 1386` don't do anythynig anymore

2021-06-16 16:03 UTC, JikaiLong commented on pages/assessment-quality-dashboard-view.js
> +			const formatedValue =  html`
Totally agree.

2021-06-16 16:04 UTC, JikaiLong commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +serverData.loadData([6606, 6608], 1386);
Thanks for letting me know. :)

2021-06-16 16:06 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +			return { value: formatedValue, noStyle };
`nit` Interesting. The rendering function tries to get `style` property but it's `undefined` which is okay/intended. Despite I like this code readability it doesn't make sense for rendering function due to it doesn't read `noStyle` property.

2021-06-16 16:07 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +			return { value: formatedValue, noStyle };
I guess you wanted write something like this 
```JS
{ value: formatedValue, style: noStyle };
```

2021-06-16 16:09 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +        ></assessment-quiz-table>`);
`nit` inconsistent indentation

2021-06-16 16:11 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +			const table = el.renderRoot.querySelector('d2l-table-wrapper').querySelector('table');
`code improvement suggestion` I assume this CSS selector should work
```JS
el.renderRoot.querySelector('d2l-table-wrapper table')
```

2021-06-16 16:12 UTC, JikaiLong commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +			const table = el.renderRoot.querySelector('d2l-table-wrapper').querySelector('table');
cool. I never tried that way. Will see if that works

2021-06-16 16:17 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +			const columnHeaders = table.querySelector('thead').querySelector('tr').querySelectorAll ('th');
`same` inconsistent style, possible simple selector, extra spaces for attribute assignments

2021-06-16 16:17 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +			const columnHeader = table.querySelector('thead').querySelector('tr').querySelector('th').querySelector('div');
`same` inconsistent style, possible simple selector, extra spaces for attribute assignments

2021-06-16 16:18 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +			expect(cells[1].querySelector('div').innerText).equal('0.19');
`same` inconsistent style, possible simple selector, extra spaces for attribute assignments

2021-06-16 16:22 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +		});
`same` inconsistent style, possible simple selector, extra spaces for attribute assignments. I'd suggest going over the whole file to adjust formatting

2021-06-16 16:23 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +		it('should show table custom cells', async() => {
missed CRLF before `it`

2021-06-16 16:23 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +		it('should open a new page when click on a custom cell', async() => {
missed CRLF before `it`

2021-06-16 16:25 UTC, JikaiLong commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +		});
True. I will fix the whole style things for the test file.

2021-06-16 16:25 UTC, Vitalii-Misechko reviewed
PR looks much better! Thank you @JikaiLong for your improvements.

2021-06-16 17:12 UTC, NicholasHallman commented on pages/assessment-quality-dashboard-view.js
> +		const redirectToQuiz = (e) => {
`nit` functions that are called by an event listener should start with `handle` e.g `handleRedirectToQuiz`

2021-06-16 17:15 UTC, NicholasHallman commented on pages/assessment-quality-dashboard-view.js
> +		const numberOfLearnerAnswers = (data) => { return { value: html`<div>${data.numberOfLearnerAnswers}</div>`, noStyle };};
`nit` These lambdas don't need to live inside the render function. Might be better to place them near the top of the file outside the class since they only need to be registered once

2021-06-16 20:02 UTC, JikaiLong commented
Added new optional config` sharedStyles` in `tableConfig` which takes a html style template and apply styles to all relative elements in the table. The test case is basically checking if the shared style template exists since the` Window.getComputedStyle(query_element) `for corresponding elements always give me default style value though the shared style works visually. Hope some can tell me if it is supposed to behave like that. 
Fixed most `nit` and style-wised problem

2021-06-17 10:04 UTC, Vitalii-Misechko commented on test/components/assessment-quiz-table/assessment-quiz-table.test.js
> +			originalOpen = window.open;
`nit` `originalOpen` will never change, therefore, it can be a constant.
```JS
const originalOpen = window.open;
beforeEach(() => {
```

2021-06-17 10:06 UTC, Vitalii-Misechko approved these changes
LGTM!

2021-06-17 13:45 UTC, NicholasHallman approved these changes
Looks fantastic thank you for all your work on this! 💯

2021-06-17 13:49 UTC, merged