Us127987 [AQ] quiz items table UI
Brightspace/insights-assessment-quality-dashboard pull request #39
Opened 2021-06-22 18:04 UTC by JikaiLong

Functional Testing
Browsers (Chrome, FF, Edge) 
- [ ]  Show Immersive Nav Bar - able to route back to the main dashboard 
- [ ]  Show Quiz Name as Header
- [ ]  Show 'Quiz Item' as second Header
 The table will include the following column headers in this order from left to right:
 - [ ]  Question Name Question Id: able to navigate to the question page(currently empty)
 - [ ]  Mean: in percentage, number below 0.5 will have cell shaded red with low opacity
 - [ ]  Popular Incorrect Answer: hide using an ellipsis if string is too long, can use tooltip to check for full string
 - [ ]  Top Lure Response Rate: number
 - [ ]  Standard Deviation: number
- [ ]   Correlation: number
- [ ]   Discrimination Index: number
- [ ]   Upper 27%: number
- [ ]   Lower 27%: number
- [ ]  Pagination works
- [ ]  Responsive on all devices

Test cases
- [ ] construct
- [ ] assessible 
- [ ] display correct data
- [ ] display correct data when pagination is used

Security, devops, perf: N/A
UX and docs
- [ ] Demo to Kevin

NOTE: The mock data is created INSIDE the component to not affect the new API implement for dashboard only. Modification is required once the quiz item API is ready.

2021-06-22 18:10 UTC, SEsseltine commented
Just as a reminder, tagging @Brightspace/draco-vis will notify all of the vis team members and wont require as much effort for each PR to tag everyone 😄

2021-06-23 09:04 UTC, Vitalii-Misechko commented on components/table/assessment-quiz-table.js
> +		<h2 class="d2l-heading-2">${this.tableConfig.heading}</h2>
Are these changes consistent with styles used on Engagement Dashboard?

2021-06-23 09:08 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +				<div class="d2l-insights-aq-dashboard-view-total-quizzes">
I assume we don't need aditional div. Could you just rename `div`'s class `d2l-insights-aq-dashboard-view-total-quizzes`  => `d2l-total-quizzes`?

2021-06-23 09:09 UTC, Vitalii-Misechko commented on consts.js
> +export const COURSE_OFFERING = 3;
I removed this file. Do you need it?

2021-06-23 09:14 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +const MEAN_TEMPLATE = (data) => { return { value: html`<div>${(data.AvgScore * 100).toFixed(2)} %</div>`, style: styleMap({ 'background-color' : (data.AvgScore < 0.5) ? 'rgba(255, 0, 0, 0.2)' : null
What if avgScore is null or undefined? Have a look at the latest changes in `assessment-quality-dashboard-view` and `renderNullOrValue` function.

2021-06-23 09:18 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +		this.serverDataMock =
It seems you need to adjust demo data that resides in `/test/server.js`.

2021-06-23 10:08 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +		this.serverDataMock =
I believe that quiz detail data will be fetched in a separate request. Have a look at [draft of API](https://github.com/Brightspace/lms/pull/11829).  @bemailloux is this assumption correct?

`proposal` Therefore, I'd suggest the following `QuizData`(serverData) design

```JS 
// fetchQuizDetail - function from dataApiClient.js that queries LMS
export class QuizData {
constructor({ fetchUserQuizDataFunc = fetchUserQuizData, fetchQuizDetailFunc= fetchQuizDetail }) {
  ...
  this._fetchQuizDetail  = fetchQuizDetail;
  this._quizDetailData = [];
}

// this method should be called in `firstUpdated` method of `quiz-item-analysis-view`
// the code is simplified and should be implemented based on `QuizData .loadData` example
async loadQuizDetailData(quizId) {
  this.isLoading = true;
  this._quizDetailData = await this._fetchQuizDetail(quizId);
  this.isLoading = false;
}

get quizDetailData() {
  return this._quizDetailData;
}

decorate(QuizData, {
  _quizDetailData: observable;
});
```

Therefore, the code will access `this.serverData.quizDetailData` instead of `this.serverData.quizzes`

2021-06-23 10:13 UTC, Vitalii-Misechko requested changes
Great start! There is a lot to do though )

2021-06-23 12:38 UTC, JikaiLong commented on consts.js
> +export const COURSE_OFFERING = 3;
Looks like the merge didn't remove it, I will remove it now.

2021-06-23 12:39 UTC, JikaiLong commented on pages/quiz-item-analysis-view.js
> +const MEAN_TEMPLATE = (data) => { return { value: html`<div>${(data.AvgScore * 100).toFixed(2)} %</div>`, style: styleMap({ 'background-color' : (data.AvgScore < 0.5) ? 'rgba(255, 0, 0, 0.2)' : null
Good point. I will make it consistent with the dashboard change yesterday.

2021-06-23 12:42 UTC, JikaiLong commented on pages/quiz-item-analysis-view.js
> +		this.serverDataMock =
Right. I asked Bryan about the API. I will follow a similar design to create a new class `QuizItemData`.

2021-06-23 13:04 UTC, JikaiLong commented on components/table/assessment-quiz-table.js
> +		<h2 class="d2l-heading-2">${this.tableConfig.heading}</h2>
Double Checked, on Engagement Dashboard it is `"d2l-heading-3"`, but the milestone page shows `"d2l-heading-2"`, I will switch to `"d2l-heading-3"` for consistence.

2021-06-23 13:32 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +		this.serverDataMock =
This way it works for me too. 👍

2021-06-23 16:57 UTC, JikaiLong commented on pages/quiz-item-analysis-view.js
> +		this.serverDataMock =
I finished the implementation and found out a new class `QuizItemData` is not needed. I added some method in `QuizData` for query fake data which I replaced the actual API fetch process since it is not there yet.

2021-06-23 17:06 UTC, JikaiLong commented on pages/quiz-item-analysis-view.js
> +const MEAN_TEMPLATE = (data) => { return { value: html`<div>${(data.AvgScore * 100).toFixed(2)} %</div>`, style: styleMap({ 'background-color' : (data.AvgScore < 0.5) ? 'rgba(255, 0, 0, 0.2)' : null
There is a very weird behavior with `renderNullOrValue` when switching pages with customize `<td>`  style based on data attribute value.  I think the reason is that the `styleMap `is applied to a `<td>` and is not immediately reset after a page is switched, therefore it is trying to render the previous CSS setting first and couldn't  find that data attribute value(like a number) and since it is `null`, `undefined` error is generated on` styleMap`. 
I made an alter fix by change the value from `null` to a string `'NULL' `and added condition check when using customized `<td>`, but I am willing to learn better ways to fix it.

2021-06-23 19:12 UTC, JikaiLong commented
Still cannot figure out what is causing the styleMap to not reset the CSS, alter way is implemented. Test cases updated using `demoQuizItemData` as well.

2021-06-24 10:32 UTC, Vitalii-Misechko commented on model/quizData.js
> +		return this._quizItemData;
You need to access `_quizItemDataProxy` here. Have a look at `serverData` getter implementation

2021-06-24 10:37 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +const StdDev_TEMPLATE = (data) => { return { value: html`<div>${data.StdDev}</div>`, style: NO_STYLE };};
`nit` StdDev_TEMPLATE => STD_DEV_TEMPLATE?

2021-06-24 10:57 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +		return this.serverData.quizItemData;
`proposal` These if/else logic can be easily removed. We just need some default data to be assigned to `this.serverData`

```JS
constructor
  this.serverData = {
    quizItemData: { quizName: null, questions: [] } // or defaultQuizItemData;
  }
  
get _activeQuiz {  
	return this.serverData.quizItemData
}
```

2021-06-24 10:59 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +				{ headerLangTerm:  'quizItems:stdDev', tooltipTextLangTerm: 'quizItems:stdDevTooltip' },
`nit` extra space

2021-06-24 11:00 UTC, Vitalii-Misechko commented on test/pages/quiz-item-analysis-view.test.js
> +				quiz-id = 1
`nit` extra spaces before and after `=`

2021-06-24 11:25 UTC, Vitalii-Misechko commented on test/pages/quiz-item-analysis-view.test.js
> +					quizItems: [
`jfyi` basically you can generate objects with only `Id`-property and it should work. For instance, `d2l-insights-assessment-dashboard-view` works with an array of objects but `d2l-insights-assessment-dashboard-view.pagination` test uses the array of arrays for `data` constant (I forget to change that) and still works. It works because it verifies that pagination properly slices `data` and ignores the data values iteself.

2021-06-24 11:29 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +					data[fieldName] = nullText;
it should return `return { value: html`${nullText}`, style: NO_STYLE };`

2021-06-24 11:34 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +const MEAN_TEMPLATE = (data) => { return { value: html`<div>${(data.AvgScore * 100).toFixed(2)} %</div>`, style: styleMap({ 'background-color' : (data.AvgScore < 0.5) ? 'rgba(255, 0, 0, 0.2)' : null
I assume this is because `renderNullOrValue` should return `return { value: html${nullText}, style: NO_STYLE };` Here's full text of it form master
```JS
		const renderNullOrValue = (fieldName, renderFunc) => {
			return function(data) {
				if (data && nullOrUndefinded(data[fieldName])) {
					return { value: html`${nullText}`, style: NO_STYLE };
				}

				return renderFunc(data);
			};
		};
```

2021-06-24 12:53 UTC, JikaiLong commented on pages/quiz-item-analysis-view.js
> +		return this.serverData.quizItemData;
make sense

2021-06-24 12:55 UTC, JikaiLong commented on test/pages/quiz-item-analysis-view.test.js
> +					quizItems: [
Interesting, let me check it out.

2021-06-24 12:59 UTC, JikaiLong commented on pages/quiz-item-analysis-view.js
> +const MEAN_TEMPLATE = (data) => { return { value: html`<div>${(data.AvgScore * 100).toFixed(2)} %</div>`, style: styleMap({ 'background-color' : (data.AvgScore < 0.5) ? 'rgba(255, 0, 0, 0.2)' : null
This is a problem I am currently investigating into, possibly a mismatch with styleMap.

2021-06-24 13:02 UTC, JikaiLong commented on model/quizData.js
> +		return this._quizItemData;
The proxy is currently not used but I will add it there.

2021-06-24 13:22 UTC, JikaiLong commented on test/pages/quiz-item-analysis-view.test.js
> +					quizItems: [
should I change the pagination in the assessment-dashboard-view tests as well?

2021-06-24 14:13 UTC, JikaiLong commented on pages/quiz-item-analysis-view.js
> +				{ headerLangTerm:  'quizItems:stdDev', tooltipTextLangTerm: 'quizItems:stdDevTooltip' },
I think it is a GIT visual bug, space looks fine if directly accessing the file.

2021-06-24 16:00 UTC, Vitalii-Misechko commented on pages/quiz-item-analysis-view.js
> +				{ headerLangTerm:  'quizItems:stdDev', tooltipTextLangTerm: 'quizItems:stdDevTooltip' },
two spaces vs one space
![image](https://user-images.githubusercontent.com/9429561/123295388-582cd380-d51e-11eb-999d-9a5c81d11eb8.png)

2021-06-24 16:00 UTC, Vitalii-Misechko commented on test/pages/quiz-item-analysis-view.test.js
> +					quizItems: [
If you don't mind It would be great

2021-06-24 17:08 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +const nullOrUndefinded = (value) => (value === null || value === undefined);
it's odd to see this line because it already exists in [the master](https://github.com/Brightspace/insights-assessment-quality-dashboard/blob/master/pages/assessment-quality-dashboard-view.js#L19) 🤷

2021-06-24 17:10 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +const nullOrUndefinded = (value) => (value === null || value === undefined);
Oh... there is merge conflict

2021-06-24 17:12 UTC, Vitalii-Misechko commented on pages/assessment-quality-dashboard-view.js
> +const nullOrUndefinded = (value) => (value === null || value === undefined);
Fixed

2021-06-24 17:14 UTC, JikaiLong commented on pages/assessment-quality-dashboard-view.js
> +const nullOrUndefinded = (value) => (value === null || value === undefined);
Yea, I noticed that too.

2021-06-24 17:15 UTC, JikaiLong commented
Me and Nick also noticed the lack of accessibility implementation, proceed to work on that.

2021-06-24 17:25 UTC, Vitalii-Misechko approved these changes
Basically, all my suggestions were included in the PR. 
Feel free to merge _after_ fixing unit tests and second approval. 
Thank you for your improvements to the PR!

2021-06-24 18:21 UTC, JikaiLong commented
All test cases are fixed to match the AQ dashboard view.

2021-06-24 18:24 UTC, NicholasHallman approved these changes
Great work!

2021-06-24 19:04 UTC, JikaiLong commented on test/pages/quiz-item-analysis-view.test.js
> +					quizItems: [
I will leave it for now. Might include the fix in the next PR.

2021-06-24 19:07 UTC, merged